### ISSUE TITLE
Install fail when using a port other than 5432

### ISSUE THREAD

**Issue by Chedi** [oVirt/ovirt-ansible-remote-db#1]
##### SUMMARY
Installation fails when using any port other thant 5432

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/chedi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
When specifying a port different from 5432 with for example
```yaml
ovirt_engine_remote_db_port: 15432
```
##### EXPECTED RESULTS
Successful installation

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {"changed": false, "msg": "unable to connect to database: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n"}
```

all the tasks that connect to the database via the unix socket will fail because the postgresql server will rename it to something like .s.PGSQL.{{ port }} (.s.PGSQL.15432 in this case) causing that exception

Impacted tasks are:
- drop engine DB
- drop engine DB user
- create engine DB user
- drop DWH DB
- drop DWH DB user
- create DWH DB user
- create DWH DB without data
- Enable PostgreSQL uuid-ossp extension

Two possible ways to fix this:

### 1- Use tcp for all database operations

As the name suggest you dont use the unix socket when connecting to postgresql running on a non default port, as there is no way (as far as I know) to force the name of the socket file in the **postgresql_db**, **postgresql_user** and **postgresql_ext** modules (the underlying psycopg2.connect dont seems to accept any option to do so). 

In such case all the operations must use a tcp connection and require specifying the host as an ip addresse or fdqn different from 127.0.0.1, ::1 and localhost as using such name will result in using **peer** and **ident** authentication mechanism by default.

```yaml
- name: drop engine DB
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ ovirt_engine_db_name }}"
    port: "{{ ovirt_engine_remote_db_port }}"
    login_host: "{{ ansible_default_ipv4.address if ovirt_engine_remote_db_port != 5432 else localhost  }}"
    state: absent
  when:
    - ovirt_engine_remote_db
    - ovirt_engine_remote_db_force
```

The inconvience here is that it will require adding one extra rule for the operation account with trusted access in pg_hba.conf config.
```
host all postgres XXX.XXX.XXX.XXX/32 trust
```
with 
```yaml
- name: add postgres trusted access
  lineinfile:
    state: present
    dest: '{{ pg_vars.data_dir }}/pg_hba.conf'
    line: 'host all postgres {{ ansible_default_ipv4.address }}/32 trust'
    regexp: '^host.*postgres.*trust$'
  when: ovirt_engine_remote_db_port != 5432
```

such rule can be removed afterward with

```yaml
- name: Delete postgres trusted access
  lineinfile: 
     dest: '{{ pg_vars.data_dir }}/pg_hba.conf'
     state: absent 
     regexp: '^.*postgres.*trust$' 
```

### 2- Linking the postgresql socket file to the expected name

This method is a little bit of a hack, and consist to linking the postgresql socket file to the expected one with

```yaml
- name: Creates directory
  file:
    path: /var/run/postgresql/ovirt
    state: directory
    owner: postgres
    group: postgres
    mode: 0755
  when: postgresql_status is failed and ovirt_engine_remote_db_port != 5432

- name: create a socket link
  file:
    src: "/var/run/postgresql/.s.PGSQL.{{ ovirt_engine_remote_db_port }}"
    dest: "/var/run/postgresql/ovirt/.s.PGSQL.5432"
    state: link
  when: postgresql_status is failed and ovirt_engine_remote_db_port != 5432
```

and then specifying the socket path on each action like this

```yaml
- name: drop engine DB
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ ovirt_engine_db_name }}"
    login_unix_socket: "{{ '/var/run/postgresql/ovirt/' if ovirt_engine_remote_db_port != 5432 else '/var/run/postgresql' }}"
    state: absent
  when:
    - ovirt_engine_remote_db
    - ovirt_engine_remote_db_force

```

The reason I'm using a different folder and not directly linking to in the original one, is for the case where another postgresql is running on the same host and creating it socket in with the default path and name.

This solution work for most the cases except for:
- Enable PostgreSQL uuid-ossp extension

as there is no explicit option like **login_unix_socket** in **postgresql_ext** module. The workarround is to pass it in the **login_host** option

```yaml
- name: Enable PostgreSQL uuid-ossp extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: 'uuid-ossp'
    db: "{{ ovirt_engine_db_name }}"
    login_host: "{{ '/var/run/postgresql/ovirt/' if ovirt_engine_remote_db_port != 5432 else '/var/run/postgresql' }}"
  when:
    - ovirt_engine_version >= '4.2'
```
